// Builds every platform output from the W3C design tokens in tokens/.
//   dist/css/alma.css        CSS custom properties (4 themes) + text style classes
//   dist/js/tokens.mjs       resolved values for JavaScript
//   dist/json/tokens.json    the ALMA artifact format (claude.ai Design System)
//   dist/dart/alma_tokens.dart  Flutter: AlmaColors ThemeExtension, spacing, motion, type
import StyleDictionary from 'style-dictionary';
import { mkdir, readFile, writeFile } from 'node:fs/promises';

const cfg = JSON.parse(await readFile('tokens/alma.config.json', 'utf8'));
const THEMES = cfg.themes.map((t) => t.id);
const HEADER = 'GENERATED by scripts/build-tokens.mjs from tokens/ — do not edit.';

async function load(theme) {
  const sd = new StyleDictionary({
    usesDtcg: true,
    log: { verbosity: 'silent', warnings: 'disabled' },
    source: ['tokens/core/*.json', 'tokens/type/*.json', `tokens/themes/${theme}.json`],
    platforms: { all: { transforms: [] } },
  });
  await sd.hasInitialized;
  return (await sd.getPlatformTokens('all')).allTokens;
}

const byTheme = {};
for (const th of THEMES) byTheme[th] = await load(th);
const base = byTheme[THEMES[0]];
const colorsOf = (th) => byTheme[th].filter((t) => t.path[0] === 'color');
const coreTokens = base.filter((t) => cfg.families.includes(t.path[0]));
const fonts = base.filter((t) => t.path[0] === 'font');
const styles = base.filter((t) => t.path[0] === 'type');

const bezier = (v) => `cubic-bezier(${v.join(', ')})`;
const coreValue = (t) => (t.path[0] === 'easing' ? bezier(t.$value) : String(t.$value));
const aliasName = (v) => v.slice(1, -1).split('.').pop();
const cssColor = (t) => (typeof t.original.$value === 'string' && t.original.$value.startsWith('{') ? `var(--${aliasName(t.original.$value)})` : t.$value);

// ---------- CSS ----------
function cssTheme(th, selector) {
  const scheme = th.startsWith('dark') ? 'dark' : 'light';
  return `${selector} {\n${colorsOf(th).map((t) => `  --${t.name}: ${cssColor(t)};`).join('\n')}\n  color-scheme: ${scheme};\n}\n`;
}
let css = `/* ${HEADER} */\n`;
css += cssTheme(THEMES[0], `:root, [data-theme="${THEMES[0]}"]`);
for (const th of THEMES.slice(1)) css += cssTheme(th, `[data-theme="${th}"]`);
css += `:root {\n${coreTokens.map((t) => `  --${t.name}: ${coreValue(t)};`).join('\n')}\n${fonts.map((t) => `  --font-${t.name}: ${t.$value};`).join('\n')}\n}\n`;
for (const s of styles) {
  const v = s.$value, fam = s.original.$value.fontFamily.slice(1, -1).split('.').pop();
  css += `.${s.name} { font-family: var(--font-${fam}); font-size: ${v.fontSize}; line-height: ${v.lineHeight}; font-weight: ${v.fontWeight}; letter-spacing: ${v.letterSpacing}; }\n`;
}

// ---------- JS ----------
const js = `// ${HEADER}\n` +
  `export const themes = ${JSON.stringify(Object.fromEntries(THEMES.map((th) => [th, Object.fromEntries(colorsOf(th).map((t) => [t.name, t.$value]))])), null, 2)};\n` +
  `export const core = ${JSON.stringify(Object.fromEntries(cfg.families.map((f) => [f, Object.fromEntries(coreTokens.filter((t) => t.path[0] === f).map((t) => [t.name, coreValue(t)]))])), null, 2)};\n` +
  `export const fonts = ${JSON.stringify(Object.fromEntries(fonts.map((t) => [t.name, t.$value])), null, 2)};\n` +
  `export const typography = ${JSON.stringify(Object.fromEntries(styles.map((s) => [s.name, s.$value])), null, 2)};\n` +
  `export default { themes, core, fonts, typography };\n`;

// ---------- ALMA artifact JSON (list-shaped) ----------
const almaValue = (t) => (typeof t.original.$value === 'string' && t.original.$value.startsWith('{') ? `{${aliasName(t.original.$value)}}` : t.original.$value);
const alma = {};
for (const key of cfg.keyOrder) {
  if (key === 'name' || key === 'version' || key === 'meta') alma[key] = cfg[key];
  else if (key === 'color') {
    alma.color = { themes: cfg.themes, tokens: colorsOf(THEMES[0]).map((t, i) => {
      const o = { name: t.name, value: Object.fromEntries(THEMES.map((th) => [th, almaValue(colorsOf(th)[i])])) };
      if (t.$description) o.usage = t.$description;
      return o;
    }) };
  } else if (key === 'type') {
    alma.type = { fonts: cfg.type.fonts, families: Object.fromEntries(fonts.map((t) => [t.name, t.$value])),
      groups: cfg.type.groups.map((g) => ({ name: g.name, family: g.family, styles: styles.filter((s) => s.path[1] === g.name).map((s) => {
        const v = s.original.$value, fam = v.fontFamily.slice(1, -1).split('.').pop();
        const o = { name: s.name, fontSize: v.fontSize, lineHeight: v.lineHeight, fontWeight: v.fontWeight, letterSpacing: v.letterSpacing };
        if (fam !== g.family) o.family = fam;
        if (s.$description) o.usage = s.$description;
        return Object.assign(o, (s.$extensions && s.$extensions.alma) || {});
      }) })) };
  } else if (cfg.families.includes(key)) {
    const fam = {};
    if (cfg.familyNotes[key]) fam.note = cfg.familyNotes[key];
    fam.tokens = coreTokens.filter((t) => t.path[0] === key).map((t) => {
      const o = { name: t.name, value: coreValue(t) };
      if (t.$description) o.usage = t.$description;
      return o;
    });
    alma[key] = fam;
  }
}

// ---------- Dart (Flutter) ----------
const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const hex2 = (n) => Math.round(n).toString(16).padStart(2, '0').toUpperCase();
function dartColor(v) {
  let m = /^#([0-9a-f]{6})([0-9a-f]{2})?$/i.exec(v);
  if (m) return `Color(0x${(m[2] || 'FF').toUpperCase()}${m[1].toUpperCase()})`;
  m = /^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+))?\s*\)$/.exec(v);
  if (m) return `Color(0x${hex2((m[4] === undefined ? 1 : +m[4]) * 255)}${hex2(+m[1])}${hex2(+m[2])}${hex2(+m[3])})`;
  throw new Error('Color no soportado en Dart: ' + v);
}
const px = (v) => { const m = /^(-?[\d.]+)(px|rem)?$/.exec(String(v)); if (!m) throw new Error('Medida no soportada: ' + v); return +(m[2] === 'rem' ? +m[1] * 16 : +m[1]).toFixed(4); };
const num = (n) => (Number.isInteger(n) ? n.toFixed(1) : String(n));
const names = colorsOf(THEMES[0]).map((t) => camel(t.name));
const dartThemeId = (th) => camel(th);
let dart = `// ${HEADER}\n// ignore_for_file: constant_identifier_names, public_member_api_docs\nimport 'dart:ui' show FontVariation;\n\nimport 'package:flutter/material.dart';\n\n`;
dart += `/// ALMA themes. [AlmaColors.of] returns the palette for each one.\nenum AlmaTheme { ${THEMES.map(dartThemeId).join(', ')} }\n\n`;
dart += `/// Every ALMA color token (semantic and component), per theme. Register it with\n/// \`ThemeData(extensions: [AlmaColors.dark])\` and read it with \`Theme.of(context).extension<AlmaColors>()!\`.\n@immutable\nclass AlmaColors extends ThemeExtension<AlmaColors> {\n`;
dart += `  const AlmaColors({\n${names.map((n) => `    required this.${n},`).join('\n')}\n  });\n\n`;
dart += colorsOf(THEMES[0]).map((t, i) => `${t.$description ? `  /// ${t.$description.replace(/\n/g, ' ')}\n` : ''}  final Color ${names[i]};`).join('\n') + '\n\n';
for (const th of THEMES) dart += `  static const AlmaColors ${dartThemeId(th)} = AlmaColors(\n${colorsOf(th).map((t, i) => `    ${names[i]}: ${dartColor(t.$value)},`).join('\n')}\n  );\n\n`;
dart += `  static AlmaColors of(AlmaTheme theme) {\n    switch (theme) {\n${THEMES.map((th) => `      case AlmaTheme.${dartThemeId(th)}:\n        return ${dartThemeId(th)};`).join('\n')}\n    }\n  }\n\n`;
dart += `  @override\n  AlmaColors copyWith({\n${names.map((n) => `    Color? ${n},`).join('\n')}\n  }) {\n    return AlmaColors(\n${names.map((n) => `      ${n}: ${n} ?? this.${n},`).join('\n')}\n    );\n  }\n\n`;
dart += `  @override\n  AlmaColors lerp(ThemeExtension<AlmaColors>? other, double t) {\n    if (other is! AlmaColors) return this;\n    return AlmaColors(\n${names.map((n) => `      ${n}: Color.lerp(${n}, other.${n}, t)!,`).join('\n')}\n    );\n  }\n}\n\n`;
const famClass = { spacing: 'AlmaSpacing', radius: 'AlmaRadius', breakpoint: 'AlmaBreakpoint', size: 'AlmaSize', icon: 'AlmaIconSize', grid: 'AlmaGrid', fontAxis: 'AlmaFontAxis' };
for (const [fam, cls] of Object.entries(famClass)) {
  const ts = coreTokens.filter((t) => t.path[0] === fam); if (!ts.length) continue;
  dart += `abstract final class ${cls} {\n${ts.map((t) => `${t.$description ? `  /// ${t.$description.replace(/\n/g, ' ')}\n` : ''}  static const double ${camel(t.name)} = ${num(px(t.$value))};`).join('\n')}\n}\n\n`;
}
dart += `abstract final class AlmaDuration {\n${coreTokens.filter((t) => t.path[0] === 'duration').map((t) => `  static const Duration ${camel(t.name.replace(/^duration-/, ''))} = Duration(milliseconds: ${parseInt(t.$value, 10)});`).join('\n')}\n}\n\n`;
dart += `abstract final class AlmaEasing {\n${coreTokens.filter((t) => t.path[0] === 'easing').map((t) => `  static const Cubic ${camel(t.name.replace(/^easing-/, ''))} = Cubic(${t.$value.map(num).join(', ')});`).join('\n')}\n}\n\n`;
const shadows = coreTokens.filter((t) => t.path[0] === 'shadow');
dart += `abstract final class AlmaShadow {\n${shadows.map((t) => {
  const m = /^(-?[\d.]+)(?:px)? (-?[\d.]+)(?:px)? ([\d.]+)(?:px)? (-?[\d.]+)(?:px)? (.+)$/.exec(t.$value);
  if (!m) throw new Error('Sombra no soportada: ' + t.$value);
  return `  static const List<BoxShadow> ${camel(t.name.replace(/^shadow-/, ''))} = <BoxShadow>[\n    BoxShadow(offset: Offset(${num(+m[1])}, ${num(+m[2])}), blurRadius: ${num(+m[3])}, spreadRadius: ${num(+m[4])}, color: ${dartColor(m[5])}),\n  ];`;
}).join('\n')}\n}\n\n`;
dart += `/// ALMA text styles. Roboto Flex with the axes of AlmaFontAxis (width and grade).\nabstract final class AlmaTypography {\n${styles.map((s) => {
  const v = s.$value, family = String(v.fontFamily).split(',')[0].replace(/["']/g, '').trim();
  return `  static const TextStyle ${camel(s.name)} = TextStyle(fontFamily: '${family}', fontSize: ${num(px(v.fontSize))}, height: ${num(+v.lineHeight)}, fontWeight: FontWeight.w${v.fontWeight}, letterSpacing: ${num(px(v.letterSpacing))}, fontVariations: <FontVariation>[FontVariation('wdth', AlmaFontAxis.fontWidth), FontVariation('GRAD', AlmaFontAxis.fontGrade)]);`;
}).join('\n')}\n}\n`;

await mkdir('dist/css', { recursive: true }); await mkdir('dist/js', { recursive: true });
await mkdir('dist/json', { recursive: true }); await mkdir('dist/dart', { recursive: true });
await writeFile('dist/css/alma.css', css);
await writeFile('dist/js/tokens.mjs', js);
await writeFile('dist/json/tokens.json', JSON.stringify(alma, null, 1) + '\n');
await writeFile('dist/dart/alma_tokens.dart', dart);
console.log(`ALMA: ${colorsOf(THEMES[0]).length} colores × ${THEMES.length} temas · ${coreTokens.length} tokens base · ${styles.length} estilos → css, js, json, dart`);
