// Puts the field's code inside ALMA's cover (artifact/project/components/Cover/preview.html), so the cover draws with
// the same code as every entity's field: entidades/semilla.mjs and entidades/campo.mjs, without their `import` and
// `export` words, go between /* @campo:start */ and /* @campo:end */. A preview is one self-contained script: it
// cannot load the generator from anywhere. Run it after changing either file (npm run build does).
// Usage: node scripts/build-portada.mjs [--check]   (--check changes nothing and fails if the cover is out of date)
import { readFileSync, writeFileSync } from 'node:fs';

const PORTADA = 'artifact/project/components/Cover/preview.html', INICIO = '/* @campo:start */', FIN = '/* @campo:end */';
const read = (p) => readFileSync(p, 'utf8');
const fuente = ['entidades/semilla.mjs', 'entidades/campo.mjs'].map((f) => read(f).replace(/^import .*$/gm, '').replace(/^export /gm, '').trim()).join('\n\n');
if (/<\/script|<!--/i.test(fuente)) throw new Error('El código del campo cerraría la etiqueta <script> de la portada');
const bloque = `${INICIO}\n  // Generated by scripts/build-portada.mjs from entidades/semilla.mjs and entidades/campo.mjs. Do not edit here.\n${fuente}\n  ${FIN}`;

const html = read(PORTADA), a = html.indexOf(INICIO), b = html.indexOf(FIN);
if (a < 0 || b < a) throw new Error(`${PORTADA} no tiene las marcas ${INICIO} … ${FIN}`);
const nuevo = html.slice(0, a) + bloque + html.slice(b + FIN.length);
if (process.argv.includes('--check')) {
  if (nuevo !== html) { console.error(`Portada: ${PORTADA} no está al día con entidades/. Corre: node scripts/build-portada.mjs`); process.exit(1); }
  console.log('Portada: el campo está al día');
} else {
  if (nuevo !== html) writeFileSync(PORTADA, nuevo);
  console.log(`Portada: ${nuevo === html ? 'sin cambios' : 'campo actualizado'} (${(bloque.length / 1024) | 0} KB entre las marcas)`);
}
